# Netlify configuration file
[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://your-backend-url.com;"
